spring:
  datasource:
    url: jdbc:mysql://localhost:3306/app
    username: root
    password: haslo
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: 8090
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 28800000
